# Generated by Django 4.2.4 on 2023-09-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_like_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_content',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
