# Generated by Django 4.2.4 on 2023-09-06 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_comment_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='likes_of_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.like'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
