# Generated by Django 4.2.4 on 2023-09-07 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_comment_post_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='liked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
