# Generated by Django 4.2.4 on 2023-09-07 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_like_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='liked',
        ),
        migrations.AlterField(
            model_name='like',
            name='post_like',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='app.post'),
        ),
    ]
