# Generated by Django 4.2.4 on 2023-09-17 22:11

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='defualtpic.jpg', null=True, upload_to=app.models.profile_image_upload_path),
        ),
    ]
