# Generated by Django 4.2.4 on 2023-09-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('passport_number', models.CharField(max_length=20)),
                ('id_number', models.CharField(max_length=20)),
                ('car_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('country_code', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=15)),
                ('agreed', models.BooleanField()),
                ('uploaded_file', models.FileField(upload_to='uploads/')),
            ],
            options={
                'verbose_name_plural': 'Form Data',
            },
        ),
    ]
