# Generated by Django 4.2.4 on 2023-11-06 22:17

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_comment_is_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='lives_in',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='defaultpic.jpg', null=True, upload_to=app.models.profile_image_upload_path),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
