# Generated by Django 4.2.4 on 2023-11-08 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_profile_image_profile_lives_in_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormData',
        ),
    ]
